[env:seeed_e1001]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 32MB
build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps = 
    https://github.com/Seeed-Projects/Seeed_GxEPD2.git
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit BusIO@^1.15.0
monitor_speed = 115200
upload_port = /dev/cu.usbserial-110
upload_speed = 460800
